### ISSUE TITLE
chamfer4D

### ISSUE THREAD

**Issue by qiaogh97** [ThibaultGROUEIX/ChamferDistancePytorch#16]
Can you support 4D in this project?

**Comment by ThibaultGROUEIX** [comment]
Hi @qiao1025566574 
The python implementation supports any dimension. There is no plan currently to have a 4d cuda chamfer but you could use 5d and add an extra dimension to your data with 0 value.
Best regards,

**Comment by qiaogh97** [comment]
Thanks a lot !!!
