### ISSUE TITLE
larger 3D point clouds

### ISSUE THREAD

**Issue by thachdo** [ThibaultGROUEIX/ChamferDistancePytorch#26]
Hello, I'm curious about 5D PCL, 6D PCL, ... what is it represented for? Do we have other axes than x, y, z?

**Comment by ThibaultGROUEIX** [comment]
For instance points + their normals.

**Comment by thachdo** [comment]
But they are in different units. Do we need to scale it, and how can we do that?

**Comment by ThibaultGROUEIX** [comment]
It's a hyperparameter up to the user. It would be application dependent.
