### ISSUE TITLE
ModuleNotFoundError: No module named 'chamfer3D.dist_chamfer_3D'; 'chamfer3D' is not a package

### ISSUE THREAD

**Issue by Master-cai** [ThibaultGROUEIX/ChamferDistancePytorch#28]
Hi, thanks for your wonderful work, but i have some problem when installing chamfer3D.

i tried to install it by the command `pip install -U .` and `python setup.py install --user` , but when i try to run the example code in your README it come out the error "ModuleNotFoundError".
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/37432881/200352442-019fe490-ae18-4b03-9dee-3a206c286a30.png">
Also, i try it with `pytorch=1.7.1` which shows the same error.
Do you have any idea about it? thx!

**Comment by ark1234** [comment]
I met same problem, how do you solve it?

**Comment by Master-cai** [comment]
> 
use this project as a self-made package.

do not install it by pip, if you have done it, uninstall it first.

then just make the module in your `python import search path` .for example, you can add it manually:
```python
import sys
sys.path.append("submodules/ChamferDistancePytorch")
import torch
import chamfer3D.dist_chamfer_3D
```

**Comment by ark1234** [comment]
It works, thank you so much!
