### ISSUE TITLE
How to build with CUDA11+?

### ISSUE THREAD

**Issue by ark1234** [ThibaultGROUEIX/ChamferDistancePytorch#29]
Thank you so much for your good work!
I have a A100 GPU, it only works for cuda11+ ,how to compile it in cuda11+. I tried to add "export TORCH_CUDA_ARCH_LIST="7.5"" on bashrc, it can compile, but did not work

**Comment by ark1234** [comment]
figure it out

**Comment by kanonjz** [comment]
> figure it out

Hi bro, how do you compile it in cuda11+?

**Comment by HanwenWangBUPT** [comment]
> > figure it out
> 
> Hi bro, how do you compile it in cuda11+?

give an example, my cuda vision is 11.3 and then install pytorch use "conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch",it maybe work.
