### ISSUE TITLE
undefined symbol for Pytorch 1.0.1

### ISSUE THREAD

**Issue by Steve-Tod** [ThibaultGROUEIX/ChamferDistancePytorch#4]
Hi, thanks for sharing.
I use Pytorch 1.0.1 and python 3.6.8.
I tried this:
```python
import torch
import dist_chamfer_idx
```
But I got:
`undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

Does your code support pytorch 1.0.1?

**Comment by Steve-Tod** [comment]
I changed to Pytorch 1.1.0 and python 3.6.9 then it works. Sorry for bothering you.

**Comment by ThibaultGROUEIX** [comment]
Great thanks for the feedback !
